generated
reduceTable
^#(
	#(10 0 #nil 245761 false ) 
	#(7 1 #reduceActionForOptionList1: 184321 false ) 
	#(8 1 #reduceActionForOptionLine__option___1: 197633 false ) 
	#(8 2 #reduceActionForOptionLine__option___2: 197634 false ) 
	#(11 1 #reduceActionForFlagForms2: 315394 false ) 
	#(10 2 #liftFirstValue: 245762 false ) 
	#(9 3 #reduceActionForOptionLine1: 228353 false ) 
	#(11 3 #reduceActionForFlagForms1: 315393 false )
	).